---
- name: create users and add packages
  hosts: hosts
  vars_files:
   - variable.yml
  tasks:
   - name: Install packages "{{pkg}}"
     yum:
       name: "{{pkg}}"
       state: absent
   - name: Creating users "{{usr}}
     user:
      name: "{{usr}}"
      state: present
